//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConceptionDevisWS {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConceptionDevisWS.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Straight.
        /// </summary>
        internal static string Enums_EAngle_Straight {
            get {
                return ResourceManager.GetString("Enums_EAngle_Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WithAngle.
        /// </summary>
        internal static string Enums_EAngle_WithAngle {
            get {
                return ResourceManager.GetString("Enums_EAngle_WithAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paint.
        /// </summary>
        internal static string Enums_EExtFinishing_Paint {
            get {
                return ResourceManager.GetString("Enums_EExtFinishing_Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roughcast.
        /// </summary>
        internal static string Enums_EExtFinishing_Roughcast {
            get {
                return ResourceManager.GetString("Enums_EExtFinishing_Roughcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wood.
        /// </summary>
        internal static string Enums_EExtFinishing_Wood {
            get {
                return ResourceManager.GetString("Enums_EExtFinishing_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hemp.
        /// </summary>
        internal static string Enums_EFillingKind_Hemp {
            get {
                return ResourceManager.GetString("Enums_EFillingKind_Hemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NaturalWool.
        /// </summary>
        internal static string Enums_EFillingKind_NaturalWool {
            get {
                return ResourceManager.GetString("Enums_EFillingKind_NaturalWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WoodenWool.
        /// </summary>
        internal static string Enums_EFillingKind_WoodenWool {
            get {
                return ResourceManager.GetString("Enums_EFillingKind_WoodenWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PVC.
        /// </summary>
        internal static string Enums_EFrameQuality_PVC {
            get {
                return ResourceManager.GetString("Enums_EFrameQuality_PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wood.
        /// </summary>
        internal static string Enums_EFrameQuality_Wood {
            get {
                return ResourceManager.GetString("Enums_EFrameQuality_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Angleless.
        /// </summary>
        internal static string Enums_EFrameStructure_Angleless {
            get {
                return ResourceManager.GetString("Enums_EFrameStructure_Angleless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ClosedAngle.
        /// </summary>
        internal static string Enums_EFrameStructure_ClosedAngle {
            get {
                return ResourceManager.GetString("Enums_EFrameStructure_ClosedAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenAngle.
        /// </summary>
        internal static string Enums_EFrameStructure_OpenAngle {
            get {
                return ResourceManager.GetString("Enums_EFrameStructure_OpenAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GlassWool.
        /// </summary>
        internal static string Enums_EInsulatorKind_GlassWool {
            get {
                return ResourceManager.GetString("Enums_EInsulatorKind_GlassWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RockWool.
        /// </summary>
        internal static string Enums_EInsulatorKind_RockWool {
            get {
                return ResourceManager.GetString("Enums_EInsulatorKind_RockWool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Styrofoam.
        /// </summary>
        internal static string Enums_EInsulatorKind_Styrofoam {
            get {
                return ResourceManager.GetString("Enums_EInsulatorKind_Styrofoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plasterboard.
        /// </summary>
        internal static string Enums_EIntFinishing_Plasterboard {
            get {
                return ResourceManager.GetString("Enums_EIntFinishing_Plasterboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Styrofoam.
        /// </summary>
        internal static string Enums_EIntFinishing_Styrofoam {
            get {
                return ResourceManager.GetString("Enums_EIntFinishing_Styrofoam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wood.
        /// </summary>
        internal static string Enums_EIntFinishing_Wood {
            get {
                return ResourceManager.GetString("Enums_EIntFinishing_Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BaseDone.
        /// </summary>
        internal static string Enums_EProjectState_BaseDone {
            get {
                return ResourceManager.GetString("Enums_EProjectState_BaseDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BuildingLicense.
        /// </summary>
        internal static string Enums_EProjectState_BuildingLicense {
            get {
                return ResourceManager.GetString("Enums_EProjectState_BuildingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EquipmentSetup.
        /// </summary>
        internal static string Enums_EProjectState_EquipmentSetup {
            get {
                return ResourceManager.GetString("Enums_EProjectState_EquipmentSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KeysGiven.
        /// </summary>
        internal static string Enums_EProjectState_KeysGiven {
            get {
                return ResourceManager.GetString("Enums_EProjectState_KeysGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OutOfWater.
        /// </summary>
        internal static string Enums_EProjectState_OutOfWater {
            get {
                return ResourceManager.GetString("Enums_EProjectState_OutOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signed.
        /// </summary>
        internal static string Enums_EProjectState_Signed {
            get {
                return ResourceManager.GetString("Enums_EProjectState_Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WallsDone.
        /// </summary>
        internal static string Enums_EProjectState_WallsDone {
            get {
                return ResourceManager.GetString("Enums_EProjectState_WallsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WorkStarted.
        /// </summary>
        internal static string Enums_EProjectState_WorkStarted {
            get {
                return ResourceManager.GetString("Enums_EProjectState_WorkStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ConceptionDevis.
        /// </summary>
        internal static string Enums_ERights_ConceptionDevis {
            get {
                return ResourceManager.GetString("Enums_ERights_ConceptionDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string Enums_ERights_None {
            get {
                return ResourceManager.GetString("Enums_ERights_None", resourceCulture);
            }
        }
    }
}
