// <auto-generated />
namespace ConceptionDevisWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManyToManyRel_Module_Composant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyToManyRel_Module_Composant));
        
        string IMigrationMetadata.Id
        {
            get { return "201604021941130_ManyToManyRel_Module_Composant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
