// <auto-generated />
namespace ConceptionDevisWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RevokedTokens1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevokedTokens1));
        
        string IMigrationMetadata.Id
        {
            get { return "201604101449121_RevokedTokens1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
