// <auto-generated />
namespace ConceptionDevisWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequiresProjectToHaveAClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiresProjectToHaveAClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201604110417330_RequiresProjectToHaveAClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
