// <auto-generated />
namespace ConceptionDevisWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenamedUserColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedUserColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201604171908390_RenamedUserColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
